//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUẢN_LÝ_SINH_VIÊN___TỰ_LÀM.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/chuyendoi", ReplyAction="http://tempuri.org/IMyService/chuyendoiResponse")]
        string chuyendoi(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/chuyendoi", ReplyAction="http://tempuri.org/IMyService/chuyendoiResponse")]
        System.Threading.Tasks.Task<string> chuyendoiAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/max", ReplyAction="http://tempuri.org/IMyService/maxResponse")]
        int max(int[] a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/max", ReplyAction="http://tempuri.org/IMyService/maxResponse")]
        System.Threading.Tasks.Task<int> maxAsync(int[] a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : QUẢN_LÝ_SINH_VIÊN___TỰ_LÀM.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<QUẢN_LÝ_SINH_VIÊN___TỰ_LÀM.ServiceReference1.IMyService>, QUẢN_LÝ_SINH_VIÊN___TỰ_LÀM.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string chuyendoi(string str) {
            return base.Channel.chuyendoi(str);
        }
        
        public System.Threading.Tasks.Task<string> chuyendoiAsync(string str) {
            return base.Channel.chuyendoiAsync(str);
        }
        
        public int max(int[] a) {
            return base.Channel.max(a);
        }
        
        public System.Threading.Tasks.Task<int> maxAsync(int[] a) {
            return base.Channel.maxAsync(a);
        }
    }
}
